r"""
\section*{Abstract}

Instruments are calibrated by matching their null-line -- that is, zero
amplitude -- to a long-time average of noise samples. Indeed, noise, if
generated by a multitude of independent events, tends to be normally
distributed, and its mean becomes repeatable. That property, however, holds
only for a very large dataset, and not for typically 8 to 12s
long seismic records cut out of that dataset. In the following, I will
demonstrate how much the means of seismic records will fluctuate, no matter
how perfectly calibrated the entire dataset might be.
"""
